# Pod description for hybrid application to be deployed on Cortex-M4 on imx8mm-mini-evk
# Uses the proof of concept hybruid runtime
#
kind: Pod
apiVersion: v1
metadata:
  name: example3
  labels:
    k3s-app: example3
spec:
    runtimeClassName: hybrid          
    containers:
      - name: example-hybrid-pod3
        image: ghcr.io/smarter-project/smart-camera-hybrid-application/hybrid_app_imx8mm:latest
        imagePullPolicy: IfNotPresent
