name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: smarter-project/rpmsg_cortexm_console_rtos_mp
          directory: rpmsg_cortexm_console_rtos/linux_remote      
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: rpmsg_cortexm_console_rtos/linux_remote/Dockerfile_mp
    
