name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    -
      name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      working-directory: rpmsg_cortexm_console_rtos/linux_remote
#      run: docker build . --file Dockerfile_mp --tag imx8mm_freertos_mp:$(date +%s)
#
